openapi: '3.0.3'
info:
  title: MLine
  version: '0.1.0'

paths:
  /gateway/v1/ping:
    get:
      responses:
        '200':
          description: OK
        '504':
          description: Failed to ping service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /gateway/v1/specifications:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositoryURL'
      responses:
        '200':
          description: OK
        '404':
          description: Failed to find specification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '504':
          description: Failed to connect to the service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /validator/v1/ping:
    get:
      responses:
        '200':
          description: OK
        '504':
          description: Failed to ping the service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /validator/v1/validate-specification:
    post:
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '400':
          description: Specification errors found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '504':
          description: Failed to connect to the service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

  /worker/v1/ping:
    get:
      responses:
        '200':
          description: OK
        '504':
          description: Failed to ping service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

components:
  schemas:
    ResponseError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    Error:
      type: object
    Hint:
      type: object
    Report:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
        hints:
          type: array
          $ref: "#/components/schemas/Hint"

    RepositoryURL:
      type: string
    
    SpecificationContents:
      type: string
