name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Validator Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/validator

      - name: Build and Push Validator
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./code/back/validator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/validator:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  integrator:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Integrator Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/integrator

      - name: Build and Push Integrator
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./code/back/integrator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/integrator:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
