name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract GateWay Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/gateway

      - name: Build and Push GateWay
        uses: docker/build-push-action@v6
        with:
          context: ./code/back/gateway
          file: ./code/back/gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gateway:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  integrator:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Integrator Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/integrator

      - name: Build and Push Integrator
        uses: docker/build-push-action@v6
        with:
          context: ./code/back/integrator
          file: ./code/back/integrator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/integrator:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  pingus:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Pingus Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/pingus

      - name: Build and Push Pingus
        uses: docker/build-push-action@v6
        with:
          context: ./code/back/pingus
          file: ./code/back/pingus/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pingus:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Validator Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/validator

      - name: Build and Push Validator
        uses: docker/build-push-action@v6
        with:
          context: ./code/back/validator
          file: ./code/back/validator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/validator:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Web-App Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/web-app

      - name: Build and Push Web-App
        uses: docker/build-push-action@v6
        with:
          context: ./code/front/web-app
          file: ./code/front/web-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/web-app:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  operations:
    runs-on: ubuntu-latest
    needs:
      - gateway
      - integrator
      - pingus
      - validator
      - web-app
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          repository: 2Delight/mline-operations
          ref: master
          token: ${{ secrets.OPERATIONS_REPO_UPDATE }}

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Tag
        run: |
          sed -i 's/TAG=.*/TAG=${{ github.sha }}/g' .env
          git add .env
          git commit -m "Tag update: ${{ github.sha }}"
          git push
